name: Full Stack CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd backend || exit

            git pull

            sudo docker build -t backend-app .

            # Stop running containers safely
            sudo docker ps -q | xargs -r sudo docker stop

            # Remove old containers
            sudo docker ps -aq | xargs -r sudo docker rm

            # Run new container
            sudo docker run -d -p 3000:3000 backend-app

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Deploy frontend to S3
        run: |
          aws s3 sync frontend/ s3://my-simple-devops-app-frontend-prasanna-2026 --delete